config/routes.rb
Rails.application.routes.draw do
  resources :articles

root 'articles#last', as: :home

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :author
end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def root_path
    latest_post = Article.order("id DESC").first
    article_path(latest_post)
  end

  def root_url
    latest_post = Article.order("id DESC").first
    article_url(latest_post)
  end




end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def last
    redirect_to article_path(Article.last) and return
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :author, :date, :content)
    end
end

app/controllers/blog_controller.rb
class BlogController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/blog_helper.rb
module BlogHelper
end

app/views/application/_aside.html.erb
<aside>
  <section class="authoraside">
    <div class=tint><%= image_tag 'profileimage.jpeg', :class => 'asideprofile' %></div>
    <h1><%= @article.author.name %></h1>
    <ul class="asidesocialmedia">
      <li><a href="#">Twitter</a></li>
      <li><a href="#">Facbook</a></li>
      <li><a href="#">Instagram</a></li>
    </ul>

    <div class="tint280x300"><%= image_tag 'http://lorempixel.com/280/300/sports/3/', :class => 'asidead' %></div>
    <a class="asideadlink" href="#">About This Ad</a>

    <article class="asidearticle">
      <h2>Sidebard Section Heading</h2>
      <p>Cillum vegan mustache cray, Wes Anderson Kickstarter sunt. Church-key aesthetic ut fashion axe, cillum culpa VHS. Ea freegan cardigan, bespoke Brooklyn vero vinyl PBR reprehenderit actually eiusmod exercitation aesthetic laboris. Dolore Etsy stumptown, magna cred officia 3 wolf moon.</p>
    </article>
  </section>

</aside>

app/views/application/_footer.html.erb
<footer class="mainfooter">
<header><h1>Most Popular Posts</h1></header>
<section class="footer4imageslink">
    <%= link_to image_tag('http://lorempixel.com/324/332/sports/4'), '/articles/06', :class => 'tint325x332 footerimg1 img-responsive' %>
    <%= link_to image_tag('http://lorempixel.com/324/332/sports/5'), '/articles/07', :class => 'tint325x332 footerimg2 img-responsive' %>
    <%= link_to image_tag('http://lorempixel.com/324/332/sports/6'), '/articles/08', :class => 'tint325x332 footerimg3 img-responsive' %>
    <%= link_to image_tag('http://lorempixel.com/324/332/sports/7'), '/articles/09', :class => 'tint325x332 footerimg4 img-responsive' %>
</section>
<div class="footeroffooter">
  <section class="brandcopyright">
    <%= link_to image_tag('theironyard.png'), 'http://theironyard.com', :class => 'ironyardlogo' %>

    <small class="copyright">The Ironyard Copyright 2013. All Rights Reserved</small>
  </section>
  <nav class="footernav">
    <ul>

      <li><%= link_to 'Nav Item 1', '#' %>&nbsp;|</li>
      <li><%= link_to 'Nav Item 2', '#' %>&nbsp;|</li>
      <li><%= link_to 'Nav Item 3', '#' %>&nbsp;|</li>
      <li><%= link_to 'Nav Item 5', '#' %></li>
    </ul>
  </nav>
</div>
</footer>

app/views/application/_hero.html.erb
<div class="herotint">
	<div class="hero">
		<div class="hero-inner">
			<section>
				<header><p><%= link_to image_tag('logo.png'), '/' %></p><p class = "blog"><%= link_to 'Surf & Paddle Co. Blog', '/' %></p></header>
				<nav>
					<ul>
						<li><%= link_to 'about', '/' %></li>
						<li><%= link_to 'search', '/' %></li>
						<li><%= link_to image_tag('search.png'), '/' %></li>
					</ul>
				</nav>
			</section>
			<h1>surf & paddle Co.</h1>
			<h2>An Ironyard Academy Project Est. Fall 2013</h2>
			<tag
		</div>
	</div>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_area :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Date</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.author %></td>
        <td><%= article.date %></td>
        <td><%= article.content %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<main id="maincontent">
  <article class="mainarticle">
    <h1><%= @article.title %></h1>

    <div class="byline">
      <address class="author">
        <a rel="author" href="#">
          <div class="tint"><%= image_tag 'profileimage.jpeg' %></div> <span class="name"><%= @article.author.name %></span></a>
      </address>
      <div class="date">
            on <time><%= @article.date.strftime("%A %b. %eth %l:%M %p") %></time></div>
    </div><!-- End of byline -->
    <section class="articlecontent">
        <%= @article.content %>
    </section>

    <section class="commentsshare">
        <ul class="readcomments">
          <li><%= image_tag 'comments.png' %></li>
          <li><p>Read Comments</p></li>
        </ul>

          <ul class="readlater">
            <li><%= image_tag 'later.png' %></li>
            <li><p>Read Later</p></li>
          </ul>

          <ul class="sharelater">
            <li><%= image_tag 'share.png' %></li>
            <li><p>Share This Post</p></li>
          </ul>
    </section>
</article>

<%= render 'aside' %>

</main>



<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/blog/home.html.erb
<main id="maincontent">
  <article class="mainarticle">
    <h1>A fantastic Engaging headline goes here</h1>
    <div class="byline">
      <address class="author">
        <a rel="author" href="#">
          <div class="tint"><%= image_tag 'profileimage.jpeg' %></div> <span class="name">Anne Maria</span></a>
      </address>
      <div class="date">
            on <time pubdate datetime="2014-10-07" title="Oct. 7th 9:22pm">Monday Oct. 7th 9:22pm</time></div>
    </div><!-- End of byline -->
    <section class="articlecontent">
      <p>Cillum vegan mustache cray, Wes Anderson Kickstarter sunt. Church-key aesthetic ut fashion axe, cillum culpa VHS. Ea freegan cardigan, bespoke Brooklyn vero vinyl PBR reprehenderit actually eiusmod exercitation aesthetic laboris. Dolore Etsy stumptown, magna cred officia 3 wolf moon.</p>

<p>Next level occupy polaroid veniam roof party, American Apparel typewriter Pinterest shabby chic disrupt High Life. Fap cillum four loko, American Apparel Schlitz voluptate aliqua DIY Echo Park veniam nostrud.</p>

  <blockquote>woah, that's radical!</blockquote>

<p>Fugiat messenger bag post-ironic put a bird on it, tousled banjo ethical occupy umami mlkshk meggings. 3 wolf moon nostrud dolore, messenger bag exercitation dolor jean shorts pariatur aliquip Banksy fap. Deep v bitters Thundercats, paleo squid ad butcher dolore fap accusamus gluten-free.Stumptown chillwave fixie irure PBR, culpa before they sold out church-key Williamsburg delectus Echo Park leggings. Blog chia incididunt lo-fi tempor elit, seitan literally proident 3 wolf moon nostrud dolore, messenger bag exercitation dolor jean shorts pariatur aliquip Banksy.</p>

<p>Wolf incididunt heirloom, chambray reprehenderit do in slow-carb Godard duis Blue Bottle quis post-ironic. Deep v bitters Thundercats, paleo squid ad butcher dolore fap accusamus gluten-free.Stumptown chillwave.</p>
    </section>

    <section class="commentsshare">
        <ul class="readcomments">
          <li><%= image_tag 'comments.png' %></li>
          <li><p>Read Comments</p></li>
        </ul>

          <ul class="readlater">
            <li><%= image_tag 'later.png' %></li>
            <li><p>Read Later</p></li>
          </ul>

          <ul class="sharelater">
            <li><%= image_tag 'share.png' %></li>
            <li><p>Share This Post</p></li>
          </ul>
    </section>
</article>

<%= render 'aside' %>

</main>

app/views/blog/index.html.erb
<h1>Blog#index</h1>
<p>Find me in app/views/blog/index.html.erb</p>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <meta content="IE=edge,chrome=1" http-equiv="X-UA-Compatible">
<link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700|Open+Sans:400italic,600italic,400,300,600,700' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Oswald:400,700,300' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Droid+Sans:400,700' rel='stylesheet' type='text/css'>

<%= csrf_meta_tags %>

    <title>Surf & Paddle</title>

    <%= stylesheet_link_tag "application" %>
     <script src="//oss.maxcdn.com/jquery/2.1.1/jquery.js"></script>
    <%= javascript_include_tag  "application" %>
  </head>

  <body>

    <%= render 'hero' %>

    <%= yield %>
<hr class="hrdivider" styl/>
    <%= render 'footer' %>


  </body>
</html>